[project]
name = "mcp-logseq-api"
version = "0.1.0"
description = "A model context protocol server for Logseq API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.9.1",
    "requests>=2.32.3",
]
